version: '2.1'
services:
  ethtestnet:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - openethereum-data:/home/openethereum/.local/share/io.parity.ethereum/chains/${CHAIN}/db
    command:
      --chain ${CHAIN}
      --jsonrpc-port 8541
      --jsonrpc-hosts all
    ports:
      - 8541:8545
      - 30303:30303
    networks:
      app_net:
        ipv4_address: 172.16.0.13
volumes:
  openethereum-data:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
        gateway: 172.16.0.1